require_relative 'overlord'

desc 'List defined routes'
task 'routes' do

  Overlord::routes.each_pair do |method, list|
    puts ":: #{method} ::"
    routes = []
    list.each do |item|
      source = item[0].source
      item[1].each do |s|
        source.sub!(/\(.+?\)/, ':'+s)
      end
      routes << source[1...-1]
    end
    puts routes.sort.join("\n")
    puts "\n"
  end

end
require 'jasmine'
load 'jasmine/tasks/jasmine.rake'
